# ----
# Site

title: GokulamBioTech
url: "https://gokulambiotech.github.io/"
baseurl:
google_analytics_key: UA-109863125-1
google_maps_javascript_api_key: AIzaSyDMYXq0MRHwat44vONYkjsy6e91JHTlfWI
disqus_shortname: https-gokulambiotech-github-io

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /Gokulamlogo.png
description: Gokulam BioTech
author:
  name: Dr. Gopinath Ramachandran
  email: crk53kris@gmail.com
  twitter: GokulamBioTech
social:
  name: Gokulam Biotech
  links:
    - "https://gokulambiotech.github.io/"
    - "http://gokulambiotech.blogspot.de/p/contact-us.html"

# -----
# Build new folders and content

collections:
  staff_members:
    _hide_content: true
  products:
    output: true
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/:year/:title"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  -
    scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  -
    scope:
      path: ""
      type: "products_info"
    values:
      layout: "page"
      _options:
        image_path:
          width: 600
          height: 600
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
  -
    scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

gems:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# permalink
#permalink: /products/fertilizers/index.html
#permalink: /products/biocomposting/index.html
#permalink: /products/biofertilizer-consortia/index.html
#permalink: /products/enhancers/index.html

# -----------
# CloudCannon

social_icons:
  - Twitter
  - Google Plus

_comments:
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  pricing_table: Update the information in the pricing tables.
  highlight: Emphasis the text
  color: The background colour used in the plan name and call to action.
  new_window: Open link in new window
