# ----
# Site

title: Gokulam Biotech
url: "https://gokulambiotech.com"
baseurl:
google_analytics_key: UA-109863125-1
google_maps_javascript_api_key: AIzaSyDMYXq0MRHwat44vONYkjsy6e91JHTlfWI
disqus_shortname: gokulambiotech
snipcart_key: "YWQ5NWI4ZjctMWMwYS00NDI0LTk2MWYtM2ZkNTc1YTJhYWM1NjM2NDc0MTc2MTAwODY1MjIy"

# Google verification Links

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/Gokulamlogo.png
description: Organic Farming - Research Based Biofertilizers Producer in India
author:
  name: Dr. Gopinath Ramachandran
  email: info@gokulambiotech.com
  twitter: GokulamBioTech
  facebook: gokulambiotechpondy
social:
  name: Gokulam Biotech
  links:
    - "https://gokulambiotech.com"
    - "http://gokulambiotech.blogspot.de"

# -----
# Build new folders and content

collections:
  people:
    output: true
    _hide_content: true
  products:
    output: true
    _hide_content: true
    _icon: shopping_cart
  certifications:
    output: true
    _hide_content: true

paginate: 5
paginate_path: "/blog/:num/:year/:title"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  -
    scope:
      path: ""
      type: "people"
    values:
      layout: "people"
      _options:
        image_path:
          width: 600
          height: 600
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
  -
    scope:
      path: "products"
    values:
      layout: "default"
      _options:
        image_path:
          width: 100
          height: 100

  -
    scope:
      path: "contact"
    values:
      full_width: false

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

